/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSobreRouteImport } from './routes/_public/sobre'
import { Route as PublicFlashcardsRouteImport } from './routes/_public/flashcards'
import { Route as PublicConfiguracoesRouteImport } from './routes/_public/configuracoes'
import { Route as PublicAbordagemRouteImport } from './routes/_public/abordagem'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardLoginDashboardRouteImport } from './routes/_dashboard/loginDashboard'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as PublicSimuladosIndexRouteImport } from './routes/_public/simulados/index'
import { Route as PublicQuestoesIndexRouteImport } from './routes/_public/questoes/index'
import { Route as PublicProvasIndexRouteImport } from './routes/_public/provas/index'
import { Route as PublicConteudosIndexRouteImport } from './routes/_public/conteudos/index'
import { Route as DashboardQuestionCollectionIndexRouteImport } from './routes/_dashboard/questionCollection/index'
import { Route as DashboardQuestionIndexRouteImport } from './routes/_dashboard/question/index'
import { Route as DashboardContentIndexRouteImport } from './routes/_dashboard/content/index'
import { Route as PublicSimuladosSimuladoRouteImport } from './routes/_public/simulados/$simulado'
import { Route as PublicProvasProvaRouteImport } from './routes/_public/provas/$prova'
import { Route as PublicConteudosConteudoIdRouteImport } from './routes/_public/conteudos/$conteudoId'
import { Route as DashboardQuestionCollectionCreateQuestionCollectionRouteImport } from './routes/_dashboard/questionCollection/createQuestionCollection'
import { Route as DashboardQuestionCollectionQuestionCollectionRouteImport } from './routes/_dashboard/questionCollection/$questionCollection'
import { Route as DashboardQuestionCreateQuestionRouteImport } from './routes/_dashboard/question/createQuestion'
import { Route as DashboardQuestionQuestionRouteImport } from './routes/_dashboard/question/$question'
import { Route as DashboardContentCreatecontentRouteImport } from './routes/_dashboard/content/createcontent'
import { Route as DashboardContentContentIdRouteImport } from './routes/_dashboard/content/$contentId'
import { Route as DashboardQuestionCollectionEdiQuestionCollectionEditRouteImport } from './routes/_dashboard/questionCollection/$ediQuestionCollection.edit'
import { Route as DashboardQuestionEditQuestionEditRouteImport } from './routes/_dashboard/question/$editQuestion.edit'
import { Route as DashboardContentEditContentEditRouteImport } from './routes/_dashboard/content/$editContent.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFlashcardsRoute = PublicFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConfiguracoesRoute = PublicConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAbordagemRoute = PublicAbordagemRouteImport.update({
  id: '/abordagem',
  path: '/abordagem',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginDashboardRoute = DashboardLoginDashboardRouteImport.update({
  id: '/loginDashboard',
  path: '/loginDashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSimuladosIndexRoute = PublicSimuladosIndexRouteImport.update({
  id: '/simulados/',
  path: '/simulados/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuestoesIndexRoute = PublicQuestoesIndexRouteImport.update({
  id: '/questoes/',
  path: '/questoes/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProvasIndexRoute = PublicProvasIndexRouteImport.update({
  id: '/provas/',
  path: '/provas/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConteudosIndexRoute = PublicConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardQuestionCollectionIndexRoute =
  DashboardQuestionCollectionIndexRouteImport.update({
    id: '/questionCollection/',
    path: '/questionCollection/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionIndexRoute = DashboardQuestionIndexRouteImport.update({
  id: '/question/',
  path: '/question/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentIndexRoute = DashboardContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicSimuladosSimuladoRoute = PublicSimuladosSimuladoRouteImport.update({
  id: '/simulados/$simulado',
  path: '/simulados/$simulado',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProvasProvaRoute = PublicProvasProvaRouteImport.update({
  id: '/provas/$prova',
  path: '/provas/$prova',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConteudosConteudoIdRoute =
  PublicConteudosConteudoIdRouteImport.update({
    id: '/conteudos/$conteudoId',
    path: '/conteudos/$conteudoId',
    getParentRoute: () => PublicRoute,
  } as any)
const DashboardQuestionCollectionCreateQuestionCollectionRoute =
  DashboardQuestionCollectionCreateQuestionCollectionRouteImport.update({
    id: '/questionCollection/createQuestionCollection',
    path: '/questionCollection/createQuestionCollection',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionCollectionQuestionCollectionRoute =
  DashboardQuestionCollectionQuestionCollectionRouteImport.update({
    id: '/questionCollection/$questionCollection',
    path: '/questionCollection/$questionCollection',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionCreateQuestionRoute =
  DashboardQuestionCreateQuestionRouteImport.update({
    id: '/question/createQuestion',
    path: '/question/createQuestion',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionQuestionRoute =
  DashboardQuestionQuestionRouteImport.update({
    id: '/question/$question',
    path: '/question/$question',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentCreatecontentRoute =
  DashboardContentCreatecontentRouteImport.update({
    id: '/content/createcontent',
    path: '/content/createcontent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentContentIdRoute =
  DashboardContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionCollectionEdiQuestionCollectionEditRoute =
  DashboardQuestionCollectionEdiQuestionCollectionEditRouteImport.update({
    id: '/questionCollection/$ediQuestionCollection/edit',
    path: '/questionCollection/$ediQuestionCollection/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuestionEditQuestionEditRoute =
  DashboardQuestionEditQuestionEditRouteImport.update({
    id: '/question/$editQuestion/edit',
    path: '/question/$editQuestion/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardContentEditContentEditRoute =
  DashboardContentEditContentEditRouteImport.update({
    id: '/content/$editContent/edit',
    path: '/content/$editContent/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/loginDashboard': typeof DashboardLoginDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/abordagem': typeof PublicAbordagemRoute
  '/configuracoes': typeof PublicConfiguracoesRoute
  '/flashcards': typeof PublicFlashcardsRoute
  '/sobre': typeof PublicSobreRoute
  '/': typeof PublicIndexRoute
  '/content/$contentId': typeof DashboardContentContentIdRoute
  '/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/question/$question': typeof DashboardQuestionQuestionRoute
  '/question/createQuestion': typeof DashboardQuestionCreateQuestionRoute
  '/questionCollection/$questionCollection': typeof DashboardQuestionCollectionQuestionCollectionRoute
  '/questionCollection/createQuestionCollection': typeof DashboardQuestionCollectionCreateQuestionCollectionRoute
  '/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/provas/$prova': typeof PublicProvasProvaRoute
  '/simulados/$simulado': typeof PublicSimuladosSimuladoRoute
  '/content': typeof DashboardContentIndexRoute
  '/question': typeof DashboardQuestionIndexRoute
  '/questionCollection': typeof DashboardQuestionCollectionIndexRoute
  '/conteudos': typeof PublicConteudosIndexRoute
  '/provas': typeof PublicProvasIndexRoute
  '/questoes': typeof PublicQuestoesIndexRoute
  '/simulados': typeof PublicSimuladosIndexRoute
  '/content/$editContent/edit': typeof DashboardContentEditContentEditRoute
  '/question/$editQuestion/edit': typeof DashboardQuestionEditQuestionEditRoute
  '/questionCollection/$ediQuestionCollection/edit': typeof DashboardQuestionCollectionEdiQuestionCollectionEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/loginDashboard': typeof DashboardLoginDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/abordagem': typeof PublicAbordagemRoute
  '/configuracoes': typeof PublicConfiguracoesRoute
  '/flashcards': typeof PublicFlashcardsRoute
  '/sobre': typeof PublicSobreRoute
  '/': typeof PublicIndexRoute
  '/content/$contentId': typeof DashboardContentContentIdRoute
  '/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/question/$question': typeof DashboardQuestionQuestionRoute
  '/question/createQuestion': typeof DashboardQuestionCreateQuestionRoute
  '/questionCollection/$questionCollection': typeof DashboardQuestionCollectionQuestionCollectionRoute
  '/questionCollection/createQuestionCollection': typeof DashboardQuestionCollectionCreateQuestionCollectionRoute
  '/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/provas/$prova': typeof PublicProvasProvaRoute
  '/simulados/$simulado': typeof PublicSimuladosSimuladoRoute
  '/content': typeof DashboardContentIndexRoute
  '/question': typeof DashboardQuestionIndexRoute
  '/questionCollection': typeof DashboardQuestionCollectionIndexRoute
  '/conteudos': typeof PublicConteudosIndexRoute
  '/provas': typeof PublicProvasIndexRoute
  '/questoes': typeof PublicQuestoesIndexRoute
  '/simulados': typeof PublicSimuladosIndexRoute
  '/content/$editContent/edit': typeof DashboardContentEditContentEditRoute
  '/question/$editQuestion/edit': typeof DashboardQuestionEditQuestionEditRoute
  '/questionCollection/$ediQuestionCollection/edit': typeof DashboardQuestionCollectionEdiQuestionCollectionEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/loginDashboard': typeof DashboardLoginDashboardRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_public/abordagem': typeof PublicAbordagemRoute
  '/_public/configuracoes': typeof PublicConfiguracoesRoute
  '/_public/flashcards': typeof PublicFlashcardsRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/': typeof PublicIndexRoute
  '/_dashboard/content/$contentId': typeof DashboardContentContentIdRoute
  '/_dashboard/content/createcontent': typeof DashboardContentCreatecontentRoute
  '/_dashboard/question/$question': typeof DashboardQuestionQuestionRoute
  '/_dashboard/question/createQuestion': typeof DashboardQuestionCreateQuestionRoute
  '/_dashboard/questionCollection/$questionCollection': typeof DashboardQuestionCollectionQuestionCollectionRoute
  '/_dashboard/questionCollection/createQuestionCollection': typeof DashboardQuestionCollectionCreateQuestionCollectionRoute
  '/_public/conteudos/$conteudoId': typeof PublicConteudosConteudoIdRoute
  '/_public/provas/$prova': typeof PublicProvasProvaRoute
  '/_public/simulados/$simulado': typeof PublicSimuladosSimuladoRoute
  '/_dashboard/content/': typeof DashboardContentIndexRoute
  '/_dashboard/question/': typeof DashboardQuestionIndexRoute
  '/_dashboard/questionCollection/': typeof DashboardQuestionCollectionIndexRoute
  '/_public/conteudos/': typeof PublicConteudosIndexRoute
  '/_public/provas/': typeof PublicProvasIndexRoute
  '/_public/questoes/': typeof PublicQuestoesIndexRoute
  '/_public/simulados/': typeof PublicSimuladosIndexRoute
  '/_dashboard/content/$editContent/edit': typeof DashboardContentEditContentEditRoute
  '/_dashboard/question/$editQuestion/edit': typeof DashboardQuestionEditQuestionEditRoute
  '/_dashboard/questionCollection/$ediQuestionCollection/edit': typeof DashboardQuestionCollectionEdiQuestionCollectionEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/perfil'
    | '/dashboard'
    | '/loginDashboard'
    | '/profile'
    | '/abordagem'
    | '/configuracoes'
    | '/flashcards'
    | '/sobre'
    | '/'
    | '/content/$contentId'
    | '/content/createcontent'
    | '/question/$question'
    | '/question/createQuestion'
    | '/questionCollection/$questionCollection'
    | '/questionCollection/createQuestionCollection'
    | '/conteudos/$conteudoId'
    | '/provas/$prova'
    | '/simulados/$simulado'
    | '/content'
    | '/question'
    | '/questionCollection'
    | '/conteudos'
    | '/provas'
    | '/questoes'
    | '/simulados'
    | '/content/$editContent/edit'
    | '/question/$editQuestion/edit'
    | '/questionCollection/$ediQuestionCollection/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/perfil'
    | '/dashboard'
    | '/loginDashboard'
    | '/profile'
    | '/abordagem'
    | '/configuracoes'
    | '/flashcards'
    | '/sobre'
    | '/'
    | '/content/$contentId'
    | '/content/createcontent'
    | '/question/$question'
    | '/question/createQuestion'
    | '/questionCollection/$questionCollection'
    | '/questionCollection/createQuestionCollection'
    | '/conteudos/$conteudoId'
    | '/provas/$prova'
    | '/simulados/$simulado'
    | '/content'
    | '/question'
    | '/questionCollection'
    | '/conteudos'
    | '/provas'
    | '/questoes'
    | '/simulados'
    | '/content/$editContent/edit'
    | '/question/$editQuestion/edit'
    | '/questionCollection/$ediQuestionCollection/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_dashboard'
    | '/_public'
    | '/login'
    | '/register'
    | '/_authenticated/perfil'
    | '/_dashboard/dashboard'
    | '/_dashboard/loginDashboard'
    | '/_dashboard/profile'
    | '/_public/abordagem'
    | '/_public/configuracoes'
    | '/_public/flashcards'
    | '/_public/sobre'
    | '/_public/'
    | '/_dashboard/content/$contentId'
    | '/_dashboard/content/createcontent'
    | '/_dashboard/question/$question'
    | '/_dashboard/question/createQuestion'
    | '/_dashboard/questionCollection/$questionCollection'
    | '/_dashboard/questionCollection/createQuestionCollection'
    | '/_public/conteudos/$conteudoId'
    | '/_public/provas/$prova'
    | '/_public/simulados/$simulado'
    | '/_dashboard/content/'
    | '/_dashboard/question/'
    | '/_dashboard/questionCollection/'
    | '/_public/conteudos/'
    | '/_public/provas/'
    | '/_public/questoes/'
    | '/_public/simulados/'
    | '/_dashboard/content/$editContent/edit'
    | '/_dashboard/question/$editQuestion/edit'
    | '/_dashboard/questionCollection/$ediQuestionCollection/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/flashcards': {
      id: '/_public/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof PublicFlashcardsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/configuracoes': {
      id: '/_public/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PublicConfiguracoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/abordagem': {
      id: '/_public/abordagem'
      path: '/abordagem'
      fullPath: '/abordagem'
      preLoaderRoute: typeof PublicAbordagemRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/loginDashboard': {
      id: '/_dashboard/loginDashboard'
      path: '/loginDashboard'
      fullPath: '/loginDashboard'
      preLoaderRoute: typeof DashboardLoginDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/simulados/': {
      id: '/_public/simulados/'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof PublicSimuladosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/questoes/': {
      id: '/_public/questoes/'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof PublicQuestoesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/provas/': {
      id: '/_public/provas/'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof PublicProvasIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/conteudos/': {
      id: '/_public/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof PublicConteudosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/questionCollection/': {
      id: '/_dashboard/questionCollection/'
      path: '/questionCollection'
      fullPath: '/questionCollection'
      preLoaderRoute: typeof DashboardQuestionCollectionIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/question/': {
      id: '/_dashboard/question/'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof DashboardQuestionIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/': {
      id: '/_dashboard/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof DashboardContentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/simulados/$simulado': {
      id: '/_public/simulados/$simulado'
      path: '/simulados/$simulado'
      fullPath: '/simulados/$simulado'
      preLoaderRoute: typeof PublicSimuladosSimuladoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/provas/$prova': {
      id: '/_public/provas/$prova'
      path: '/provas/$prova'
      fullPath: '/provas/$prova'
      preLoaderRoute: typeof PublicProvasProvaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/conteudos/$conteudoId': {
      id: '/_public/conteudos/$conteudoId'
      path: '/conteudos/$conteudoId'
      fullPath: '/conteudos/$conteudoId'
      preLoaderRoute: typeof PublicConteudosConteudoIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_dashboard/questionCollection/createQuestionCollection': {
      id: '/_dashboard/questionCollection/createQuestionCollection'
      path: '/questionCollection/createQuestionCollection'
      fullPath: '/questionCollection/createQuestionCollection'
      preLoaderRoute: typeof DashboardQuestionCollectionCreateQuestionCollectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/questionCollection/$questionCollection': {
      id: '/_dashboard/questionCollection/$questionCollection'
      path: '/questionCollection/$questionCollection'
      fullPath: '/questionCollection/$questionCollection'
      preLoaderRoute: typeof DashboardQuestionCollectionQuestionCollectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/question/createQuestion': {
      id: '/_dashboard/question/createQuestion'
      path: '/question/createQuestion'
      fullPath: '/question/createQuestion'
      preLoaderRoute: typeof DashboardQuestionCreateQuestionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/question/$question': {
      id: '/_dashboard/question/$question'
      path: '/question/$question'
      fullPath: '/question/$question'
      preLoaderRoute: typeof DashboardQuestionQuestionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/createcontent': {
      id: '/_dashboard/content/createcontent'
      path: '/content/createcontent'
      fullPath: '/content/createcontent'
      preLoaderRoute: typeof DashboardContentCreatecontentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/$contentId': {
      id: '/_dashboard/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof DashboardContentContentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/questionCollection/$ediQuestionCollection/edit': {
      id: '/_dashboard/questionCollection/$ediQuestionCollection/edit'
      path: '/questionCollection/$ediQuestionCollection/edit'
      fullPath: '/questionCollection/$ediQuestionCollection/edit'
      preLoaderRoute: typeof DashboardQuestionCollectionEdiQuestionCollectionEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/question/$editQuestion/edit': {
      id: '/_dashboard/question/$editQuestion/edit'
      path: '/question/$editQuestion/edit'
      fullPath: '/question/$editQuestion/edit'
      preLoaderRoute: typeof DashboardQuestionEditQuestionEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/content/$editContent/edit': {
      id: '/_dashboard/content/$editContent/edit'
      path: '/content/$editContent/edit'
      fullPath: '/content/$editContent/edit'
      preLoaderRoute: typeof DashboardContentEditContentEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardLoginDashboardRoute: typeof DashboardLoginDashboardRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardContentContentIdRoute: typeof DashboardContentContentIdRoute
  DashboardContentCreatecontentRoute: typeof DashboardContentCreatecontentRoute
  DashboardQuestionQuestionRoute: typeof DashboardQuestionQuestionRoute
  DashboardQuestionCreateQuestionRoute: typeof DashboardQuestionCreateQuestionRoute
  DashboardQuestionCollectionQuestionCollectionRoute: typeof DashboardQuestionCollectionQuestionCollectionRoute
  DashboardQuestionCollectionCreateQuestionCollectionRoute: typeof DashboardQuestionCollectionCreateQuestionCollectionRoute
  DashboardContentIndexRoute: typeof DashboardContentIndexRoute
  DashboardQuestionIndexRoute: typeof DashboardQuestionIndexRoute
  DashboardQuestionCollectionIndexRoute: typeof DashboardQuestionCollectionIndexRoute
  DashboardContentEditContentEditRoute: typeof DashboardContentEditContentEditRoute
  DashboardQuestionEditQuestionEditRoute: typeof DashboardQuestionEditQuestionEditRoute
  DashboardQuestionCollectionEdiQuestionCollectionEditRoute: typeof DashboardQuestionCollectionEdiQuestionCollectionEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardLoginDashboardRoute: DashboardLoginDashboardRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardContentContentIdRoute: DashboardContentContentIdRoute,
  DashboardContentCreatecontentRoute: DashboardContentCreatecontentRoute,
  DashboardQuestionQuestionRoute: DashboardQuestionQuestionRoute,
  DashboardQuestionCreateQuestionRoute: DashboardQuestionCreateQuestionRoute,
  DashboardQuestionCollectionQuestionCollectionRoute:
    DashboardQuestionCollectionQuestionCollectionRoute,
  DashboardQuestionCollectionCreateQuestionCollectionRoute:
    DashboardQuestionCollectionCreateQuestionCollectionRoute,
  DashboardContentIndexRoute: DashboardContentIndexRoute,
  DashboardQuestionIndexRoute: DashboardQuestionIndexRoute,
  DashboardQuestionCollectionIndexRoute: DashboardQuestionCollectionIndexRoute,
  DashboardContentEditContentEditRoute: DashboardContentEditContentEditRoute,
  DashboardQuestionEditQuestionEditRoute:
    DashboardQuestionEditQuestionEditRoute,
  DashboardQuestionCollectionEdiQuestionCollectionEditRoute:
    DashboardQuestionCollectionEdiQuestionCollectionEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicAbordagemRoute: typeof PublicAbordagemRoute
  PublicConfiguracoesRoute: typeof PublicConfiguracoesRoute
  PublicFlashcardsRoute: typeof PublicFlashcardsRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicConteudosConteudoIdRoute: typeof PublicConteudosConteudoIdRoute
  PublicProvasProvaRoute: typeof PublicProvasProvaRoute
  PublicSimuladosSimuladoRoute: typeof PublicSimuladosSimuladoRoute
  PublicConteudosIndexRoute: typeof PublicConteudosIndexRoute
  PublicProvasIndexRoute: typeof PublicProvasIndexRoute
  PublicQuestoesIndexRoute: typeof PublicQuestoesIndexRoute
  PublicSimuladosIndexRoute: typeof PublicSimuladosIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAbordagemRoute: PublicAbordagemRoute,
  PublicConfiguracoesRoute: PublicConfiguracoesRoute,
  PublicFlashcardsRoute: PublicFlashcardsRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicConteudosConteudoIdRoute: PublicConteudosConteudoIdRoute,
  PublicProvasProvaRoute: PublicProvasProvaRoute,
  PublicSimuladosSimuladoRoute: PublicSimuladosSimuladoRoute,
  PublicConteudosIndexRoute: PublicConteudosIndexRoute,
  PublicProvasIndexRoute: PublicProvasIndexRoute,
  PublicQuestoesIndexRoute: PublicQuestoesIndexRoute,
  PublicSimuladosIndexRoute: PublicSimuladosIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
